# Generated by Django 3.0.2 on 2020-03-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='confirmed_cases',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='population',
            field=models.IntegerField(null=True),
        ),
    ]
