# Generated by Django 3.0.2 on 2020-03-19 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20200319_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='nl_name_1',
        ),
    ]
