# Generated by Django 3.0.2 on 2020-03-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_remove_area_nl_name_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='point_type',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
