# Generated by Django 3.0.2 on 2020-03-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_lab_point_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
