# Generated by Django 3.0.4 on 2020-03-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_auto_20200319_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='nl_name_1',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
